FROM consol/ubuntu-omd-labs:latest
MAINTAINER The Sakuli team.  <sakuli@consol.de>

ENV REFRESHED_AT 2016-10-27

#RUN mkdir $OMD_DEMO/etc/check_mysql_health/
#COPY ["./CheckMySQLHealthSakuli.pm", "$OMD_DEMO/etc/check_mysql_health/"]
COPY ["./CheckMySQLHealthSakuli.pm", "/opt/omd/sites/demo/eXXtc/check_mysql_health/"]
