FROM consol/omd-labs-ubuntu

MAINTAINER Simon Meggle "simon.meggle@consol.de"
ENV REFRESHED_AT 2017-04-11

ARG ANSIBLE_SAKULI=/root/ansible_sakuli
# branch from where to checkout Sakuli OMD-Addon-dir "omd"
ARG SOURCE_BRANCH=dev
ADD ansible_sakuli $ANSIBLE_SAKULI

RUN env > /root/.env

# -- sparse checkout Sakuli OMD-Addon-dir "omd"
WORKDIR $ANSIBLE_SAKULI/sakuli/
# checkout the Sakuli source there
ENV SRCDIR $ANSIBLE_SAKULI/sakuli/src
# use git protocol if possible
ENV REMOTE_GIT git://github.com/ConSol/sakuli.git
# fallback if git protocol is not possible
ENV REMOTE_HTTPS https://github.com/ConSol/sakuli.git
# checkout only this folder
ENV SPARSEDIR src/common/src/main/resources/org/sakuli/common/setup/omd
RUN echo "Built from $REMOTE_GIT/$SOURCE_BRANCH" > /root/sakuli_git_info && cat /root/sakuli_git_info
RUN /bin/bash -c "mkdir $SRCDIR && pushd $SRCDIR && git init &&\
  (git remote add -f origin $REMOTE_GIT || git remote set-url origin $REMOTE_HTTPS) &&\
  git fetch --tags origin &&\
  git config core.sparseCheckout true &&\
  echo "$SPARSEDIR" > .git/info/sparse-checkout &&\
  git checkout $SOURCE_BRANCH &&\
  rm -rf $SRCDIR/.git &&\
  popd &&\
  ln -s src/$SPARSEDIR files"

# -- Run the Ansible playbook to install the Sakuli addons
# $NEW_SITENAME is borrowed as build ARG in the base image
ENV SITENAME=$NEW_SITENAME
RUN echo "Config Site $NEW_SITENAME" && \
  /omd/versions/default/bin/ansible-playbook \
  -i localhost, $ANSIBLE_SAKULI/playbook.yml \
  -c local \
  -e SITENAME=$SITENAME

WORKDIR /opt/omd/sites/$NEW_SITENAME

# CMD is borrowed from the base image
