
:imagesdir: ../../../images
[[docker-images]]
==== Sakuli Docker Images
[#git-edit-section]
:page-path: docs/manual/execution/containerized/docker-images.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}


Docker allows you to run a Sakuli test in an isolated environment, called "container", which is always started off from the same base image. This ensures that tests always run under equal conditions.

[[docker-image-os-types]]
===== Image OS types

The repository's subfolder https://github.com/ConSol/sakuli/tree/master/docker[`./docker`] contains all source files Sakuli docker images are made of. Currently we provide images on https://hub.docker.com[DockerHub] for:

* CentOS 7 (https://hub.docker.com/r/consol/sakuli-centos-xfce/[consol/sakuli-centos-xfce], https://hub.docker.com/r/consol/sakuli-centos-xfce-java/[consol/sakuli-centos-xfce-java])
* Ubuntu 14.04 LTS (https://hub.docker.com/r/consol/sakuli-ubuntu-xfce/[consol/sakuli-ubuntu-xfce], https://hub.docker.com/r/consol/sakuli-ubuntu-xfce-java/[consol/sakuli-ubuntu-xfce-java])

[[docker-image-tags]]
===== Image tags

The build process on DockerHub is triggered by Github hooks; that means that you are always getting the current version for the two branches

* *master* -&gt; image tag "*latest*": contains the latest stable release of Sakuli
* *dev* -&gt; image tag "*dev*": contains the latest snapshot version of Sakuli

[[docker-image-architecture]]
===== Architecture of Sakuli Containers

Each Sakuli docker image is installed with the following components:

* Desktop environment (http://www.xfce.org[*Xfce4*])
* VNC-Server (default VNC port `5901`)
* https://github.com/kanaka/noVNC[*noVNC*] - HTML5 VNC client (default http port `6901`)
* Java JRE 8
* Browsers:
** Mozilla Firefox + Java Plugin
** Google Chrome (Java-Plugin is no longer supported)
* http://sahi.co.in[*Sahi OS 5*]
* https://github.com/ConSol/sakuli[*Sakuli*] in the latest stable version

The running containers are accessible with VNC (default password: _sakuli_) by:

* *VNC viewer*: `DOCKER_HOST:5901`
* *noVNC HTML5 client*: link: http://localhost:6901/vnc_auto.html?password=sakuli[]

[[docker-images-get-images]]
===== Get Sakuli Docker Images

The following example command pulls the CentOS7 image from https://hub.docker.com/r/consol/sakuli-centos-xfce/[DockerHub]:

[source,bash]
----
docker pull consol/sakuli-centos-xfce
----

Alternatively, you can build this image from the sources:

[source,bash]
----
git clone https://github.com/ConSol/sakuli.git
docker build -t consol/sakuli-centos-xfce docker/sakuli-centos-xfce .
----

.Start/test a Sakuli container

Once you have pulled/built the image, you can start a container on top of it which binds port `5901/tcp` and `6901/tcp` to localhost (on native docker installations; $DOCKER_IP on boot2docker):

[source,bash]
----
# default tag "latest" = Sakuli stable
docker run -it -p 5901:5901 -p 6901:6901 consol/sakuli-centos-xfce
# tag "dev" = Sakuli Snapshot version of dev branch
docker run -it -p 5901:5901 -p 6901:6901 consol/sakuli-centos-xfce:dev
----

The container will execute a small headless self-test and exit afterwards. Read on to learn how to execute your own JavaScript or Java based tests within this containers.

[[docker-javascript-based-test]]
===== Run JavaScript based Test

There are three important lines in the `Dockerfile` of each Sakuli image which define what has to be done on a container start:

[source,Dockerfile]
----
ENV SAKULI_TEST_SUITE /root/sakuli/example_test_suites/example_xfce
ENTRYPOINT ["/root/scripts/sakuli_startup.sh"]
CMD ["run $SAKULI_TEST_SUITE"]
----

* `ENTRYPOINT` is the command which is executed once the container is started with `docker run`.
* `CMD` is the default argument for `ENTRYPOINT`, that is, to run a test suite set by a variable.
* `ENV SAKULI_TEST_SUITE` is set to the path of a test suite which has to run when the container starts. By default, this is set to the built-in folder `/root/sakuli/example_test_suites/example_xfce`.

There is more than one way to integrate a custom testsuite in a container, discussed in the following.

Assume you want to run a suite called `suite_1` located on your host at the path `/home/myuser/my-sakuli-testsuites` - use one of the following ways:

[[docker-run-command]]
====== docker run command

Mount the suite folder on your host into the container and override `CMD` from Dockerfile (=argument for `ENTRYPOINT`) with custom parameters for the Sakuli starter `sakuli`. In this way you can also give further parameters to Sakuli e.g. to use another browser (`-browser chrome`).

[source,bash]
----
# running tests in chrome
~$ docker run -it -p 5901:5901 -p 6901:6901 consol/sakuli-centos-xfce 'run "$SAKULI_TEST_SUITE" -browser chrome'
----

To get all possible command line parameters call `docker run consol/sakuli-ubuntu-xfce -help`.

CMD can be overwritten in two ways:

.1) Using the command line

[source, bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -v "/home/myuser/my-sakuli-testsuites:/my-sakuli-testsuites" consol/sakuli-centos-xfce 'run /my-sakuli-testsuites/suite_1'
----

This command will

 * mount the test suites folder to `/my-sakuli-testsuites` within the container
 * execute the suite `suite_1`

.2) Using docker-compose

See <<docker-compose-run-command>>.

[[docker-environmen-variable]]
====== Environment variable `SAKULI_TEST_SUITE`

Mount a folder on your host into the container and override the environment variable `SAKULI_TEST_SUITE`.

.1) Using the command line

[source,bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901   \\
     -v "/home/myuser/my-sakuli-testsuites:/my-sakuli-testsuites"   \\
     -e "SAKULI_TEST_SUITE=/my-sakuli-testsuites/suite_1"   \\
     consol/sakuli-ubuntu-xfce
----

.2) Using docker-compose

See <<docker-compose-environmen-variable>>.

[[docker-java-based-test]]
===== Run Java based test

Also for Sakuli test writen in Java and executed through https://maven.apache.org[Maven], we provide to preconfigured docker images:

* https://hub.docker.com/r/consol/sakuli-centos-xfce-java/[consol/sakuli-centos-xfce-java]
* https://hub.docker.com/r/consol/sakuli-ubuntu-xfce-java/[consol/sakuli-ubuntu-xfce-java].

For more information about how to write a Java based Sakuli test see <<sakuli_java_dsl>>. Now take a look at the important lines in the _Dockerfile_ which define how the container will start:

[source,Dockerfile]
----
WORKDIR /opt/maven
ENTRYPOINT ["/root/scripts/start_hook.sh"]
CMD ["mvn clean test"]
----

* `WORKDIR` is set to the path, where the maven build will be executed. By default, this is set to the built-in example folder `/opt/maven`.
* `ENTRYPOINT` is the command which is executed once the container is started with `docker run`.
* `CMD` is the default argument for `ENTRYPOINT`, what will trigger the Maven build, which contains the Java based Sakuli tests.

Assume you want to run the Sakuli end-2-end test from your Maven project located at the path `/home/myuser/my-sakuli-maven-project` you can executed the Maven build in the inside of the Sakuli container like follow:

.1) Using the command line

[source, bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -v "/home/myuser/my-sakuli-maven-project:/opt/maven" consol/sakuli-ubuntu-xfce-java
----

This command will

 * mount the test suites folder to `/home/myuser/my-sakuli-maven-project` within the container
 * execute the maven build with default command `mvn clean test`

If you want to for example also build youre maven artifacts over `mvn install` override the default command like follow:

[source,bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -v "/home/myuser/my-sakuli-maven-project:/opt/maven" consol/sakuli-ubuntu-xfce-java 'mvn clean install'
----

.2) Using docker-compose
See <<docker-compose-java-based-test>>.

[[docker-vnc-env-variables]]
===== Override VNC environment variables

The following VNC environment variables can be overwritten at the `docker run` phase to customize your desktop environment inside the container:

* `VNC_COL_DEPTH`, default: `24`
* `VNC_RESOLUTION`, default: `1280x1024`
* `VNC_PW`, default: `sakuli`

For example, the password for VNC could be set like this:

[source,bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -e "VNC_PW=my-new-password"  \\
     consol/sakuli-ubuntu-xfce
----

[[docker-further-information]]
===== Further Information

Further information about the usage of Sakuli docker containers can be found at:

* Publications:
** *https://labs.consol.de/sakuli/development/2016/10/14/sakuli-java-dsl.html[Containerized UI-Tests in Java with Sakuli and Docker]*
* Presentations:
** *https://speakerdeck.com/toschneck/containerized-end-2-end-testing-containerdays-2016-in-hamburg[Containerized End-2-End-Testing - ContainerDays 2016 Hamburg]*
** *https://rawgit.com/toschneck/presentation/sakuli-testautomation-day/index.html#/[Containerized End-2-End-Testing - ConSol CM Testing]*
* Example projects on GitHub:
** *https://github.com/ConSol/sakuli-examples[ConSol/sakuli-examples]*
** *https://github.com/toschneck/sakuli-example-bakery-testing[toschneck/sakuli-example-bakery-testing]*
** *https://github.com/ConSol/sakuli-example-testautomation-day[ConSol/sakuli-example-testautomation-day]*
