
:imagesdir: ../../../images
[[docker-images]]
==== Sakuli Docker Images
[#git-edit-section]
:page-path: docs/manual/execution/containerized/docker-images.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}


Docker allows you to run a Sakuli test in an isolated environment, called "container", which is always started off from the same base image. This ensures that tests always run under equal conditions.

[[docker-image-os-types]]
===== Image OS types

The repository's subfolder https://github.com/ConSol/sakuli/tree/master/docker[`./docker`] contains all source files Sakuli docker images are made of. Currently we provide images on https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=sakuli-&starCount=0[DockerHub - Sakuli Images] for:

[cols="<,<,<,<"]
|===
|Docker image |OS |UI |Test execution

|`consol/sakuli-centos-xfce` |CentOS 7 |Xfce4 |Tests in JavaScript (Rhino Engine)
|`consol/sakuli-centos-xfce-java` |CentOS 7 |Xfce4 |Java 8, Maven, TestNG-Test
|`consol/sakuli-ubuntu-xfce` |Ubuntu 16.04 |Xfce4 |Tests in JavaScript (Rhino Engine)
|`consol/sakuli-ubuntu-xfce-java` |Ubuntu 16.04 |Xfce4 |Java 8, Maven, TestNG-Test
|`consol/sakuli-centos-icewm` |CentOS 7 |IceWM |Tests in JavaScript (Rhino Engine)
|`consol/sakuli-centos-icewm-java` |CentOS 7 |IceWM |Java 8, Maven, TestNG-Test
|`consol/sakuli-ubuntu-icewm` |Ubuntu 16.04 |IceWM |Tests in JavaScript (Rhino Engine)
|`consol/sakuli-ubuntu-icewm-java` |Ubuntu 16.04 |IceWm |Java 8, Maven, TestNG-Test
|===

[[docker-image-tags]]
===== Image tags

The build process on DockerHub is triggered by Github hooks; that means that you are always getting the current version for the two branches

* *master* -&gt; image tag "*latest*": contains the latest stable release of Sakuli
* *dev* -&gt; image tag "*dev*": contains the latest snapshot version of Sakuli

[[docker-image-architecture]]
===== Architecture of Sakuli Containers

Each Sakuli docker image is installed with the following components:

* Desktop environment (http://www.xfce.org[*Xfce4*])
* VNC-Server (default VNC port `5901`)
* https://github.com/kanaka/noVNC[*noVNC*] - HTML5 VNC client (default http port `6901`)
* Java JRE 8
* Browsers:
** Mozilla Firefox + Java Plugin
** Google Chrome (Java-Plugin is no longer supported)
* http://sahi.co.in[*Sahi OS 5*]
* https://github.com/ConSol/sakuli[*Sakuli*] in the latest stable version

Since version `1.1.0` all containers run as non-root user.
The running containers are accessible with VNC (default password: `sakuli`) by:

* *VNC viewer*: `DOCKER_HOST:5901`
* *noVNC HTML5 client*: link: http://localhost:6901/vnc_auto.html?password=sakuli[]

[[docker-images-get-images]]
===== Get Sakuli Docker Images

The following example command pulls the CentOS7 image from https://hub.docker.com/r/consol/sakuli-centos-xfce/[DockerHub]:

[source,bash]
----
~$ docker pull consol/sakuli-centos-xfce
----

Alternatively, you can build this image from the sources:

[source,bash]
----
~$ git clone https://github.com/ConSol/sakuli.git
~$ docker build -t consol/sakuli-centos-xfce docker/sakuli-centos-xfce .
----

.Start/test a Sakuli container

Once you have pulled/built the image, you can start a container on top of it which binds port `5901/tcp` and `6901/tcp` to localhost (on native docker installations; $DOCKER_IP on boot2docker):

[source,bash]
----
# default tag "latest" = Sakuli stable
~$ docker run -it -p 5901:5901 -p 6901:6901 consol/sakuli-centos-xfce
# tag "dev" = Sakuli Snapshot version of dev branch
~$ docker run -it -p 5901:5901 -p 6901:6901 consol/sakuli-centos-xfce:dev
----

The container will execute a small headless self-test and exit afterwards. Read on to learn how to execute your own JavaScript or Java based tests within this containers.

[[docker-javascript-based-test]]
===== Run JavaScript based Test

There are three important lines in the `Dockerfile` of each Sakuli image which define what has to be done on a container start:

[source,Dockerfile]
----
ENV SAKULI_TEST_SUITE $SAKULI_ROOT/test
ENTRYPOINT ["/dockerstartup/startup.sh"]
----

* `ENTRYPOINT` is the command which is executed once the container is started with `docker run`.
* `ENV SAKULI_TEST_SUITE` is set to the path of a test suite which has to run when the container starts. By default, this is set to the built-in folder `/headless/sakuli/test` which contains already a small example.

There is more than one way to integrate a custom testsuite in a container, discussed in the following.

Assume you want to run a suite called `suite_1` located on your host at the path `/home/myuser/my-sakuli-testsuites` - use one of the following ways:

[[docker-run-command]]
====== docker run command

Mount the suite folder on your host into the container and override `CMD` from Dockerfile (=argument for `ENTRYPOINT`) with custom parameters for the Sakuli starter `sakuli`. In this way you can also give further parameters to Sakuli e.g. to use another browser (`-browser chrome`).

[source,bash]
----
# running tests in chrome
~$ docker run -it -p 5901:5901 -p 6901:6901 consol/sakuli-centos-xfce run /headless/sakuli/test -browser chrome
----

To get all possible command line parameters call `docker run consol/sakuli-ubuntu-xfce -help`.

CMD can be overwritten in two ways:

.1) Using the command line

[source, bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -v "/home/myuser/my-sakuli-testsuites:/my-sakuli-testsuites" consol/sakuli-centos-xfce run /my-sakuli-testsuites/suite_1
----

This command will

 * mount the test suites folder to `/my-sakuli-testsuites` within the container
 * execute the suite `suite_1`

.2) Using docker-compose

See <<docker-compose-run-command>>.

[[docker-environmen-variable]]
====== Environment variable `SAKULI_TEST_SUITE`

Mount a folder on your host into the container and overwrite the environment variable `SAKULI_TEST_SUITE`.

.1) Using the command line

[source,bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901   \\
     -v "/home/myuser/my-sakuli-testsuites:/my-sakuli-testsuites"   \\
     -e "SAKULI_TEST_SUITE=/my-sakuli-testsuites/suite_1"   \\
     consol/sakuli-ubuntu-xfce
----

.2) Using docker-compose

See <<docker-compose-environmen-variable>>.

[[docker-java-based-test]]
===== Run Java based test

Also for Sakuli test writen in Java and executed through https://maven.apache.org[Maven], we provide to preconfigured docker images: https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=sakuli-java&starCount=0[consol/sakuli-xxx-xxx-java]. For more information about how to write a Java based Sakuli test see <<sakuli-java-dsl>>. Now take a look at the important lines in the _Dockerfile_ which define how the container will start:

[source,Dockerfile]
----
ENV SAKULI_TEST_SUITE /opt/maven
WORKDIR $SAKULI_TEST_SUITE
ENTRYPOINT ["/root/scripts/start_hook.sh"]
----

* `ENV SAKULI_TEST_SUITE` is set to the path of a test suite which has to run when the container starts. By default, this is set to `/opt/maven` which contains already a small example.
* `WORKDIR` is set to the path, where the maven build will be executed. By default, this is set to the built-in example folder `/opt/maven`.
* `ENTRYPOINT` is the script which is executed once the container is started with `docker run`. It starts the vnc environment and executes by default `mvn clean test`.

Assume you want to run the Sakuli end-2-end test from your Maven project located at the path `/home/myuser/my-sakuli-maven-project` you can executed the Maven build in the inside of the Sakuli container like follow:

.1) Using the command line

[source, bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -v /home/myuser/my-sakuli-maven-project:/opt/maven consol/sakuli-ubuntu-xfce-java
----

This command will

 * mount the test suites folder to `/home/myuser/my-sakuli-maven-project` within the container
 * execute the maven build with default command `mvn clean test`

If you want to for example also build youre maven artifacts over `mvn install` overwrite the default command like follow:

[source,bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -v /home/myuser/my-sakuli-maven-project:/opt/maven consol/sakuli-ubuntu-xfce-java mvn clean install
----

.2) Using docker-compose
See <<docker-compose-java-based-test>>.


[[docker-extend-a-image]]
===== Extend a Sakuli Image with your own software

Since `1.1.0` the Sakuli image run as non-root user per default, so that mean, if you want to extend the image and install software, you have to switch in the `Dockerfile` back to the `root` user:

[source,bash]
----
## Custom Dockerfile
FROM consol/sakuli-centos-xfce:v1.1.0

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2017-03-17
ENV TZ=Europe/Berlin

## Install a PDF viewer
USER 0
RUN yum install -y libsane-hpaio http://get.code-industry.net/public/master-pdf-editor-4.0.30_qt5.x86_64.rpm \
    && yum clean all
## switch back to default user
USER 1984
----

===== Change User of running Sakuli Container

Per default, since version `1.1.0` all container processes will executed with user id `1984`. You can chnage the user id like follow:

.Using root (user id `0`)

Add the `--user` flag to your docker run command:

[source]
----
~$ docker run -it --user 0 -p 6911:6901 consol/sakuli-ubuntu-xfce
----

.Using user and group id of host system

Add the `--user` flag to your docker run command:

[source]
----
~$ docker run -it -p 6911:6901 --user $(id -u):$(id -g) consol/sakuli-ubuntu-xfce
----

[[docker-vnc-env-variables]]
===== Override VNC environment variables

The following VNC environment variables can be overwritten at the `docker run` phase to customize your desktop environment inside the container:

* `VNC_COL_DEPTH`, default: `24`
* `VNC_RESOLUTION`, default: `1280x1024`
* `VNC_PW`, default: `sakuli`

For example, the password for VNC could be set like this:

[source,bash]
----
~$ docker run -it -p 5901:5901 -p 6901:6901 -e "VNC_PW=my-new-password"  \\
     consol/sakuli-ubuntu-xfce
----

===== Create Screenhots for Sakuli tests

Due to the fact, that your application under test is running in the container specific UI environment, it's also recommend to create the screenhot snippets for the <<sakuli-testdefintion>> in the inside of the container. This prevent some issues with recognizing images because of bad image compression, see <<image-recognition-problem>>.

====== Use `takeScreenshot` method
To get a new screenshot of some application window, you can modify you current test case and add for example the bellow code snippets of the method <<Region.takeScreenshot>>:
[[source,javascript]]
-----
//entire screen:
env.takeScreenshot("/tmp/my-screenshot.png");

//specific region
new RegionRectangle(0,0,100,100).takeScreenshot("/tmp/my-screenshot.png");

//extended region of an existing one
new Region().find("calculator-logo.png").grow(200,200).takeScreenshot("/tmp/my-screenshot.png");
-----

After the test suite run, you can copy out the created screenshot from docker container, if needed crop it with some image manipulating tool, and add it to our test suite.

[[source,bash]]
-----
~$ docker cp <containter-id>:/tmp/my-scrot-screenshot.png $(pwd)/my-testsuite/
~$ ls -la my-testsuite/
-----

====== Use `scrot` tool
Before using *https://wiki.ubuntuusers.de/Scrot/[Scrot]* prepare your container UI like you will needed for the screenshot via VNC `http://<dockerhost>:<mapped-port>/vnc_auto.html?password=sakuli`. If you wan't to stop the sakuli test execution on a particular point, just use the <<Environment.sleep>> method:

[[source,javascript]]
-----
    new Application("/usr/bin/gnome-calculator").open();
    env.sleep(Number.MAX_VALUE);
-----

The test case will stop at the above defined position. Then you can login to the container via `docker exec` and create a new screenshot with the `scrot <filename>` command. If you use the `scrot -s` flag you can select a rectangle, over the VNC control page `http://<docker-host>:<mapped-port>/vnc_auto.html?password=sakuli`.

[[source,bash]]
-----
~$ docker exec -it <container-id> bash
~$ scrot -s /tmp/my-scrot-screenshot.png
~$ ls -la /tmp/*.png
-rw-rw-rw- 1 default root 35329 Aug 29 15:28 /tmp/my-scrot-screenshot.png
-----

Now you can copy out the created screenshot from docker container and add it to our test suite.

[[source,bash]]
----
~$ docker cp <containter-id>:/tmp/my-scrot-screenshot.png $(pwd)/my-testsuite/
----

===== View only VNC
To prevent unwanted control over the VNC connection, it's possible to set environment variable `VNC_VIEW_ONLY=true`. If set the docker startup script will create a random cryptic password for the control connection and use the value of `VNC_PW` for the view only connection.

[[source,bash]]
----
~$ docker run -it -p 6901:6901 -e VNC_VIEW_ONLY=true  consol/sakuli-ubuntu-xfce
----

[[docker-https-sahi]]
===== Writing HTTPS Sahi web tests
Depending on the Sahi proxy, Sakuli will break the HTTPS connections between the website and test engine. Due to that case it is necessary to import the URL specific self-signed certificates like described at <<sahi-https>>. In a containerized environment we need to prepare the browser before the tests starts with the expected certificates like described at <<sahi-https-automatic-certificate-usage>>. For example if you use the Firefox browser you can do the following steps:

. Start your preferred Sakuli docker image with `docker run -it -p 6901:6901 consol/sakuli-ubuntu-xfce bash` to enter the container and connect into it by VNC http://localhost:6901/vnc_auto.html?password=sakuli

. Start Sahi dashboard:

    ~$ cd $SAKULI_ROOT/sahi/userdata/bin && ./start_dashboard.sh

. Create the firefox certificates for https://labs.consol.de like described at <<sahi-https-accept-self-signed, Sahi HTTPS - Accept self-signed certificates>>

. Now copy the following created files to a folder at your dockerhost:
    * Sahi fake certificates

    ~$ mkdir -p ssl_files
    ~$ export CONTAINER_ID=<your-docker-container-id>
    ~$ docker cp $CONTAINER_ID:/headless/sakuli/sahi/userdata/certs ssl_files/sahi_certs

    * Firefox certificate store

    ~$ mkdir -p ssl_files/ff_profile
    ~$ docker cp $CONTAINER_ID:/headless/sakuli/sahi/userdata/browser/ff/profiles/sahi0/cert8.db ssl_files/ff_profile/
    ~$ docker cp $CONTAINER_ID:/headless/sakuli/sahi/userdata/browser/ff/profiles/sahi0/key3.db  ssl_files/ff_profile/
    ~$ docker cp $CONTAINER_ID:/headless/sakuli/sahi/userdata/browser/ff/profiles/sahi0/cert_override.txt ssl_files/ff_profile/

. After this you should have the following structure:

    ~$ tree ssl_files
    ssl_files
    ├── ff_profile
    │   ├── cert8.db
    │   ├── cert_override.txt
    │   └── key3.db
    └── sahi_certs
        ├── labs_consol_de
        ├── sahi_example_com
        ├── shavar_services_mozilla_com
        └── tiles_services_mozilla_com
    2 directories, 7 files

. Update the permissions to ensure that the files can be read by container user:

    ~$ chmod a+rw ssl_files/

. At least you have just to add the files to the correct place in Docker image `Dockerfile`:

    FROM consol/sakuli-ubuntu-xfce
    ### INSTALL sahi https certificats
    COPY ssl_files/ff_profile $SAKULI_ROOT/sahi/config/ff_profile_template
    COPY ssl_files/sahi_certs $SAKULI_ROOT/sahi/userdata/certs

[[docker-images-known-issues]]
===== Known Issues

[[docker-images-known-issues-chromium-crash]]
====== Chromium crashes

According to https://github.com/ConSol/docker-headless-vnc-container[ConSol/docker-headless-vnc-container] issue https://github.com/ConSol/docker-headless-vnc-container/issues/53[Chromium crashes with high VNC_RESOLUTION #53] there is a problem when you use some graphic/work intensive websites in the Docker container (especially with high resolutions e.g. `1920x1080`). It can happen that Chromium crashes without any specific reason. The problem there is the too small `/dev/shm` size in the container. Currently there is no other way, as define this size on startup via `--shm-size` option, see https://github.com/ConSol/docker-headless-vnc-container/issues/53#issuecomment-347265977[ConSol/docker-headless-vnc-container #53 - Solution]:

    docker run --shm-size=256m -it -p 6901:6901 -e VNC_RESOLUTION=1920x1080 consol/sakuli-centos-xfce run <your-test-suite>

[[docker-further-information]]
===== Further Information

Further information about the usage of Sakuli docker containers can be found at:

* <<openshift>>
* <<kubernetes>>
* https://github.com/ConSol/omd-labs-docker[Containerized OMD]
* Publications:
** https://jaxenter.de/sakuli-testing-monitoring-container-54374[JAXenter: End-2-End-Testing und -Monitoring im Container-Zeitalter]
** https://www.informatik-aktuell.de/entwicklung/methoden/graphical-user-interface-gui-in-containern-testen.html[Informatik Aktuell: Software-Test im Container: So können Sie Graphical User Interfaces mit Docker und Sakuli testen]
** https://labs.consol.de/sakuli/development/2016/10/14/sakuli-java-dsl.html[Containerized UI-Tests in Java with Sakuli and Docker]
* Presentations:
** https://speakerdeck.com/toschneck/containerized-end-2-end-testing-containerdays-2016-in-hamburg[Containerized End-2-End-Testing - ContainerDays 2016 Hamburg]
** https://rawgit.com/toschneck/presentation/sakuli-testautomation-day/index.html#/[Containerized End-2-End-Testing - ConSol CM Testing]
* Example projects on GitHub:
** https://github.com/ConSol/sakuli-examples[ConSol/sakuli-examples]
** https://github.com/toschneck/sakuli-example-bakery-testing[toschneck/sakuli-example-bakery-testing]
** https://github.com/ConSol/sakuli-example-testautomation-day[ConSol/sakuli-example-testautomation-day]
