apiVersion: v1
kind: Template
labels:
  template: sakuli-e2e-run-pod-gitvol
metadata:
  annotations:
    description: Sakuli End-2-End testing client template (run as pod with mounted gitvolumen for the test suite)
    iconClass: icon-beaker
    tags: consol, sakuli, ubuntu, xfce
    version: 1.1.0
  creationTimestamp: null
  name: sakuli-e2e-run-pod-gitvol
### template parameter defined via `oc process -f this.yaml -v PARAMETER=value`
parameters:
- description: The name for the E2E test suite.
  name: E2E_TEST_NAME
  required: true
  value: sakuli-my-example
- description: 'Custom hostname for http service route.  Leave blank for default hostname, e.g.: <E2E_TEST_NAME-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
- description: 'Sakuli End-2-End image, see `docker search sakuli`'
  name: IMAGE
  required: true
  value: consol/sakuli-ubuntu-xfce
- description: Git repository where the Sakuli test suite is stored
  name: GIT_TEST_SUITE_REPO
  value: https://github.com/ConSol/sakuli-examples
- description: Git revision which sould be used for git checkout of the Sakuli test suite. For example to use a branch `development` or any git hash `7f00938bc89d3b95707e5458a49beaef99b0ab7e`.
  name: GIT_TEST_SUITE_REVISION
  value: master
- description: Path to the Sakuli test suite is stored at the GIT_TEST_SUITE_REPO
  name: GIT_TEST_SUITE_PATH
  value: docker-xfce/part_01/example_xfce
### Configuration of OpenShift objects
objects:
### POD config (run one time)
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      application: ${E2E_TEST_NAME}
    name: ${E2E_TEST_NAME}-pod
  spec:
    ### ensure that the pod won't start again
    restartPolicy: Never
    dnsPolicy: ClusterFirst
    terminationGracePeriodSeconds: 5
    containers:
    - name: ${E2E_TEST_NAME}-pod-c1
      image: ${IMAGE}
      imagePullPolicy: Always
      env:
        - name: JVM_HEAP_XMX_MAX
          value: '350'
        - name: TZ
          value: 'Europe/Berlin'
          ### logs have to be writen in a writable path
        - name: SAKULI_LOG_FOLDER
          value: '/headless/sakuli/logs'
        ### set e.g. debug level
        #- name: LOG_LEVEL_SAKULI
        # value: 'DEBUG'
        ### define browser over env var
        #- name: TESTSUITE_BROWSER
        #  value: 'chrome'
      volumeMounts:
      - mountPath: /headless/sakuli/test
        name: vol-test
      args:
        # - --tail-log #make normal UI startup to connect via: oc rsh <pod-name> bash
        - run
        - /headless/sakuli/test/${GIT_TEST_SUITE_PATH}
        ### run in chrome via command line
        # - run
        # - /headless/sakuli/test
        # - -browser
        # - chrome
        ### set e.g. debug level via command line
        #- -D
        #- log.level.sakuli=DEBUG
      ### checks that vnc server is up and running
      livenessProbe:
        tcpSocket:
          port: 5901
        initialDelaySeconds: 1
        timeoutSeconds: 1
      ### checks if http-vnc connection is working
      readinessProbe:
        httpGet:
          path: /
          port: 6901
          scheme: HTTP
        initialDelaySeconds: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 750m
          memory: 2200Mi
    volumes:
    - name: vol-test
      # ensure gitRepo volumes are allowed in openshift, see docu.
      gitRepo:
        repository: ${GIT_TEST_SUITE_REPO}
        revision: ${GIT_TEST_SUITE_REVISION}
        directory: .
### Service -> POD config
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Sakuli client vnc and http port
    labels:
      application: ${E2E_TEST_NAME}
    name: ${E2E_TEST_NAME}-ser
  spec:
    ports:
    - name: http-port-tcp
      protocol: TCP
      port: 6901
      targetPort: 6901
    - name: vnc-port-tcp
      protocol: TCP
      port: 5901
      targetPort: 5901
    selector:
      application: ${E2E_TEST_NAME}
### Route -> Service config
- apiVersion: v1
  id: ${E2E_TEST_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for vnc's http service.
    labels:
      application: ${E2E_TEST_NAME}
    name: ${E2E_TEST_NAME}-http
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${E2E_TEST_NAME}-ser
    port:
      targetPort: http-port-tcp
      