site_name: sakuli
site_url: https://sakuli.readthedocs.org
repo_url: https://github.com/ConSol/sakuli.git
site_description: Sakuli Documentation
docs_dir: docs
markdown_extensions: [toc,fenced_code]
pages:
  - index: README.md