
:imagesdir: ../../../images

[[forwarder]]
==== Forwarder Concept
[#git-edit-section]
:page-path: docs/manual/integration/forwarder-concept.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

After a test execution has been completed Sakuli can process or better *forward* the test results to a certain third party system, e.g. a monitoring system, file output or other third-party systems. The processing is done by a so called Sakuli Forwarder.

Feel free to develop another forwarder or ask us to do this. Currently Sakuli is providing forwarder for following output formats:

include::forwarder-overview.adoc[]

[[forwarder-step-case]]
===== Step / Case Forwarders

Usually the forwarder is invoked after the whole test suite is completed and the result of the test suite is processed.
With release `1.2` a new forwarder feature has been introduced, which allows to process the result of not only whole test suites, but also of test cases and test steps, which have been already executed. This behaviour can be controlled by the test developer, who can specify within the test case resp. test step, whether the results shall be immediately processed after the execution of the test case resp. step.

To forward the results of a certain test case, the forward flag in the saveResult shall be set to true, as shown in the example below.
[source, java]
----
    testCase.saveResult(true);
----

To forward the results of a certain test step, the forward flag in the endOfStep shall be set to true, as shown in the example below.
[source, java]
----
    testCase.endOfStep("Calculation",30, 50, true);
----

[[forwarder-templates]]
==== Forwarder Templates
With release `1.1` Sakuli introduced the http://jtwig.org/[Jtwig] template engine, which is used for generating the output of the Sakuli test suite for certain forwarders. With release `1.2` in addition to link:checkmk.adoc[Check_MK Forwarder] also link:omd-gearman.adoc[Gearman Forwarder] supports Jtwig templates.

Using templates for the forwarder output makes it possible to easily modify the output of Sakuli and adapt it without the need to release a new Sakuli version.

Here we want to describe how Jtwig is working, how to use a customized template and what you have to pay attention to.

===== JTwig template

http://jtwig.org/[Jtwig] is a template engine based on Java, which has a simple and understandable syntax und is easy to use. The following snippet shows an example of a Jtwig template used in Sakuli.

[source, xml]
----
    {% for testStep in testCase.stepsAsSortedSet %}
        , step "{{ testStep.name }}"$whitespace$
        {% if (testStep.state.error) %}
            EXCEPTION: {{ errorMessageCreator.exceptionMessage(testStep) }}
        {% else %}
            over runtime ({{ testStep.duration }}s/warn at {{ testStep.warningTime }}s)
        {% endif %}
    {% endfor %}
----

The input for this template is the `testCase` object, which has a set ot test steps. The template iterates over all the steps and prints certain step information based on the state of the test step.

The whole http://jtwig.org/[Jtwig] feature set is supported and can be used within the Sakuli forwarder.
For more detailed information about Jtwig templates, please refer to http://jtwig.org/[Jtwig].

===== Customized Jtwig Functions

http://jtwig.org/[Jtwig] comes with a list of functions like `abs`, `concat` etc, which can be used within a template. In addition to the standard functions, Jtwig supports the implementation and injection of custom functions. Sakuli provides following custom functions:

* `git-link:src/core/src/main/java/org/sakuli/services/forwarder/configuration/AbbreviateFunction.java[link-text="abbreviate", mode="view", link-window="_blank"]` - The function abbreviates a certain string to a specified length. The implementation is based on the StringUtils.abbreviate method from the Apache commons library.
* `git-link:src/core/src/main/java/org/sakuli/services/forwarder/configuration/ExtractScreenshotFunction.java[link-text="extractScreenshot", mode="view", link-window="_blank"]` - The function extracts the screenshot from a specified test data entity, which contains an exception.
* `git-link:src/core/src/main/java/org/sakuli/services/forwarder/configuration/GetOutputDurationFunction.java[link-text="getOutputDuration", mode="view", link-window="_blank"]` - The function returns the formatted duration for a specified test entity.
* `git-link:src/core/src/main/java/org/sakuli/services/forwarder/configuration/GetOutputStateFunction.java[link-text="getOutputState", mode="view", link-window="_blank"]` - The function returns the `git-link:src/core/src/main/java/org/sakuli/datamodel/state/SakuliState.java[link-text="OutputState", mode="view", link-window="_blank"]` for a specified SakuliState.
* `git-link:src/core/src/main/java/org/sakuli/services/forwarder/configuration/IsBlankFunction.java[link-text="isBlank", mode="view", link-window="_blank"]` - The function checks whether the specified string parameter is blank.
* `git-link:src/core/src/main/java/org/sakuli/services/forwarder/configuration/UnixTimestampConverterFunction.java[link-text="convertToUnixTimestamp", mode="view", link-window="_blank"]` - The function converts a date object into an unix timestamp.
* `git-link:src/core/src/main/java/org/sakuli/services/forwarder/configuration/GetTestDataEntityTypeFunction.java[link-text="getTestDataEntityType", mode="view", link-window="_blank"]` - The function retrieves the type of a provided AbstractTestDataEntity, which currently could be one of: TestSuite, TestCase or TestCaseStep.

Please refer to the Sakuli git-link:src/common/src/main/resources/org/sakuli/common/config/templates[link-text="default Jtwig templates", mode="view", link-window="_blank"], to see the custom functions in action.

.Handling of white spaces and new lines

The forwarder implementation provides a special handling of white spaces and new lines within the templates. For this feature the `jtwig-spaceless-extension` has been used, which comes with a SpaceRemover interface. This has been implemented by the `LeadingWhitespaceRemover`. The `LeadingWhitespaceRemover` is configured in the twig template engine and removes all leading whitespaces for every line and all line endings within the template. It can be activated by adding the text snippet or the whole template within the following tags `{% spaceless %}` and `{% endspaceless %}`.
The `LeadingWhitespaceRemover` has been introduced, to make the implementation and maintaining of the templates easier.

Since the leading white spaces and the new lines are removed, some special placeholder have been introduced, which are replaced by the real characters at the end of the template generation:
* `$whitespace$` - the placeholder will be replaced by a real white space.
* `$newline$` - the placeholder will be replaced by a new line `&#39;\n&#39;`.

.Using a customized templates

Sakuli provides a default template set, which is placed within the templates directory under `__SAKULI_HOME__/config/templates` within the Sakuli home folder (e.g. the default Check_MK templates can be found in a subdirectory `check_mk`).

The property `sakuli.forwarder.template.folder` defines the path to the main.twig template for the respective forwarder. The default value is set to `${sakuli.home.folder}/config/templates`.

Before customizing a default template, it is essential to copy the templates to a new location and configure that location as the template location in Sakuli, otherwise installing a new Sakuli release would overwrite the modified templates within the config directory.

.Structure of the default main template

Generally the forwarder is expecting to find a certain template file named `main.twig` within the configured template directory. The default `main.twig` template doesn't contain the whole output, but includes further templates to make the single templates more readable. Since the templates are fully customizable, the user can decide how the templates are structured, whether to use nested templates or to define everything within a single file.

The following snippet shows the default `main.twig` template provided by Sakuli for the Check_MK forwarder. This template is also showing the use of the spaceless extension and the special character for a new line.

[source, xml]
----
    {% spaceless %}
    {% import 'error_message_creator.twig' as errorMessageCreator %}
        <<<local>>>$newline$
        {% include 'performance_data.twig' %}
        {% include 'short_summary.twig' %}
        {% include 'detailed_summary.twig' %}
        $newline$
    {% endspaceless %}
----

.Supported Forwarder

* <<check_mk>> (since `1.1`)
* <<omd-gearman>> (since `1.2`)
