
:imagesdir: ../../images

[[json-forwarder]]
=== JSON Forwarder

[#git-edit-section]
:page-path: docs/manual/integration/json-forwarder.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

This page describes how the test suite results of Sakuli can be serialized to a JSON file, which can be read by other 3rd party systems.


[[json-forwarder-configuraiton]]
===== Configuraiton of JSON forwarder

The JSON forwarder provides two properties to customise its behaviour. Using those properties it is possible to enable resp. disable the forwarder and to change the folder, to which the json output is written. The JSON forwarder is enabled by default. Both properties can be edited in `sakuli.properties` in the folder containing the test suites (you can copy the lines from `__SAKULI_HOME__/conf/sakuli-default.properties`):

[source,properties]
----
__INST_DIR__/example_test_suites/sakuli.properties:

# DEFAULT: true
sakuli.forwarder.json.enabled

#DEFAULT: ${sakuli.log.folder}/_json
sakuli.forwarder.json.dir
----

[[json-forwarder-output]]
===== Output of JSON forwarder
After executing the example test suite, the json output can be found under `_logs/_json` folder of the test suite. The name of the output file is based on the following pattern:

[source]
----
`<test_suite_id>_<timestamp>.json`
----

For every test suite run, a new json output is generated as soon as the forwarder is enabled.

[[json-forwarder-usage]]
===== Usage of JSON forwarder output
Currently the output, generated by the JSON forwarder, is used as an input for the Sakuli GUI. The Sakuli GUI is displaying the result of the test suite executed by Sakuli. It is possible to navigate through all the test cases, test steps and test actions for a certain test suite.
Furthermore the JSON output can be used as an input for third party systems, e.g. some monitoring system.
