#### POD config (run one time)
apiVersion: v1
kind: Namespace
metadata:
  name: sakuli
---
apiVersion: v1
kind: Pod
metadata:
  namespace: sakuli
  labels:
    application: test-sakuli-kub
  name: test-sakuli-kub
spec:
  ### ensure that the pod won't start again
  restartPolicy: Never
  dnsPolicy: ClusterFirst
  terminationGracePeriodSeconds: 5
  containers:
  - name: test-sakuli-kub
    ##  TODO TS: remove tag after finishing
    image: consol/sakuli-ubuntu-xfce:v1.1.0-SNAPSHOT-218_docker_usermod_openshift
    imagePullPolicy: Always
    args:
      ### make normal UI startup to connect via: oc rsh <pod-name> bash
      #- '--tail-log'
      ### run in chrome
      # - 'run'
      # - '/headless/sakuli/test'
      # - '-browser'
      # - 'chrome'
      ### set e.g. debug level
      #- '-D'
      #- 'log.level.sakuli=DEBUG'
    ### checks that vnc server is up and running
    livenessProbe:
      tcpSocket:
        port: 5901
      initialDelaySeconds: 1
      timeoutSeconds: 1
    ### checks if http-vnc connection is working
    readinessProbe:
      httpGet:
        path: /
        port: 6901
        scheme: HTTP
      initialDelaySeconds: 1
      timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: test-sakuli-kub
  namespace: sakuli
  name: test-sakuli-kub
spec:
  externalName: test-sakuli-kub
  ports:
  - name: http-port-tcp
    protocol: TCP
    port: 6901
    targetPort: 6901
    nodePort: 32001
  - name: vnc-port-tcp
    protocol: TCP
    port: 5901
    targetPort: 5901
    nodePort: 32002
  selector:
    application: test-sakuli-kub
  type: NodePort