
[[TestCase]]
==== TestCase

[#git-edit-section]
:page-path: docs/manual/testdefinition/sakuli-api-testcase.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

TestCase - initializes the Sakuli object and sets the warning and critical time for this test case.

*Params*

* warningTime `number` - threshold in seconds. If the threshold is set to 0,
 the execution time will never exceed, so the state will be always OK!
* criticalTime `number` - threshold in seconds. If the threshold is set to 0,
 the execution time will never exceed, so the state will be always OK!
* optImagePathArray `Array.&lt;String&gt;` - (optional) Path or Array of Paths to the folder containing the image patterns
 for these test cases.

*Returns*: - an initialized Sakuli object.
*Example*
[source,js]
----
var testCase = new TestCase(20,30, "path-to/image-folder-name");
----

*Members*

* link:#TestCase[TestCase]
* link:#TestCase.addImagePaths[TestCase.addImagePaths(imagePaths)]
* link:#TestCase.endOfStep[TestCase.endOfStep(stepName, optWarningTime)]
* link:#TestCase.handleException[TestCase.handleException(e)]
* link:#TestCase.saveResult[TestCase.saveResult()]
* link:#TestCase.getID[TestCase.getID()]
* link:#TestCase.getLastURL[TestCase.getLastURL()]
* link:#TestCase.getTestCaseFolderPath[TestCase.getTestCaseFolderPath()]
* link:#TestCase.getTestSuiteFolderPath[TestCase.getTestSuiteFolderPath()]
* link:#TestCase.throwException[TestCase.throwException(message, screenshot)]


[[TestCase.addImagePaths]]
.TestCase.addImagePaths(imagePaths)

Adds the additional paths to the current image library of the TestCase.
If a relative path is assigned, the current testcase folder will be used as current directory.

*Params*

* imagePaths `string` - one or more path strings


[[TestCase.endOfStep]]
.TestCase.endOfStep(stepName, optWarningTime)

A step allows to sub-divide a case to measure logical units, such as "login", "load report" etc. in its
particular runtime. When a case starts, Sakuli starts a "step" timer. It gets read out, stored with the
step name, and resetted each time endOfStep() is called.
If the step runtime exceeds the step threshold (second parameter, optional), the step is saved with state
"WARNING" (there is no CRITICAL state).

*Params*

* stepName `String`
* optWarningTime `number` - (optional) threshold in seconds, default = 0. If the threshold is set to 0,
 the execution time will never exceed, so the state will be always OK!


[[TestCase.handleException]]
.TestCase.handleException(e)

Handles any Exception or Error. The handleException function calls the Java backend and stores the Exception
for further processing.

Use it at the end of a catch-block.

*Params*

* e `Error` - any Exception or Error

*Example*
[source,js]
----
try {
  ... do something
} catch (e) {
    sakuli.handleException(e);
}
----


[[TestCase.saveResult]]
.TestCase.saveResult()

Saves the results of the current test case for further processing.

Should be called in finally-block of the test case:

*Example*
[source,js]
----
try {
    ... do something
} catch (e) {
    sakuli.handleException(e);
} finally {
    sakuli.saveResult();
}
----


[[TestCase.getID]]
.TestCase.getID()

Returns the *current* id of this test case.

*Returns*: `String` - id

[[TestCase.getLastURL]]
.TestCase.getLastURL()

Updates and returns the URL of the last visited URL

*Returns*: `String` - last visited URL

[[TestCase.getTestCaseFolderPath]]
.TestCase.getTestCaseFolderPath()

*Returns*: `String` - the folder path of the current testcase.

[[TestCase.getTestSuiteFolderPath]]
.TestCase.getTestSuiteFolderPath()

*Returns*: `String` - the folder path of the current testcase.

[[TestCase.throwException]]
.TestCase.throwException(message, screenshot)

Creates a new test case based exception with an optional screenshot at the calling time.
Will be called from sakuli.js or in side of 'org.sakuli.javaDSL.AbstractSakuliTest'.

*Params*

* message `String` - error message
* screenshot `Boolean` - enable / disable screenshot functionality

