
:imagesdir: ../../images

[[Key]]
==== Key

[#git-edit-section]
:page-path: docs/manual/testdefinition/sakuli-api-key.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

All non-character keys are represented by _Key_ constants which can be used in type functions.

The following link:#Key[Key] values are available:

`SPACE`, `ENTER`, `BACKSPACE`, `TAB`, `ESC`, `UP`, `RIGHT`, `DOWN`, `LEFT`, `PAGE_UP`, `PAGE_DOWN`, `DELETE`, `END`,
`HOME`, `INSERT`, `F1`, `F2`, `F3`, `F4`, `F5`, `F6`, `F7`, `F8`, `F9`, `F10`, `F11`, `F12`, `F13`, `F14`, `F15`,
`SHIFT`, `CTRL`, `ALT`, `ALTGR`, `META`, `CMD`, `WIN`, `PRINTSCREEN`, `SCROLL_LOCK`, `PAUSE`, `CAPS_LOCK`, `NUM0`,
`NUM1`, `NUM2`, `NUM3`, `NUM4`, `NUM5`, `NUM6`, `NUM7`, `NUM8`, `NUM9`, `SEPARATOR`, `NUM_LOCK`, `ADD`, `MINUS`,
`MULTIPLY`, `DIVIDE`, `DECIMAL`, `CONTEXT`


*Example*

Press `F1`:
[source,js]
----
env.type(Key.F1);
----

Close a window by typing the shortcut `ALT + F4`
[source,js]
----
// the second parameter is the held (="modifier") key
env.type(Key.F4, Key.ALT);
----

Open the file manager on Windows with shortcut `WIN + e`:
[source,js]
----
env.type("e", Key.META)
----

Do something application specific with shortcut `CTRL + ALT + b` (CTRL + ALT = ALTGR):
[source,js]
----
env.type("b", Key.ALTGR)
----

Closing an window over typing the short cut `ALT + F4`:

[source,js]
----
env.type(Key.F4, Key.ALT);
----

*Using `Key.ALTGR` on Unix:*

TIP: To enable the key command `ALTGR` on unix systems please bind it to `CTRL + ALT`. For more information
see http://unix.stackexchange.com/questions/157834/how-to-bind-altgr-to-ctrl-alt[stackexchange.com - how-to-bind-altgr-to-ctrl-alt].



*Members*

* link:#Key[Key]
