---

- name: "Configure Sakuli E2E checks for Site: {{ SITENAME }}"
  hosts: all
  environment:
    OMD_ROOT: "/opt/omd/sites/{{ SITENAME }}"
  tasks:

    # temporärer fix, bis neue RPMs gebaut sind
    - name: copy coreconfig.yaml
      copy:
        src: coreconfig.yml
        dest: /opt/omd/versions/default/share/sakuli/setup/

    - name: configure Sakuli extension
      become: yes
      become_user: "{{ SITENAME }}"
      become_method: "su"
      become_flags: "-"
      command: make "{{ item }}"
      with_items:
        - "{{ GRAPHER }}"
        - "screenshot_history"
        - "gearman"
      args:
        chdir: "$OMD_ROOT/share/sakuli/setup"

    - name: set Nagios core
      command: "omd config {{ SITENAME }} set CORE nagios"

    - name: set timezone
      shell: echo 'TZ=Europe/Berlin' >> $OMD_ROOT/etc/environment
