# Sakuli example docker-compose.yml file with 2 different container running the same tests in parrallel

sakuli-example-centos:
  image: consol/sakuli-centos-xfce
  volumes:
  - ../example_test_suites:/root/my_test_suites
  environment:
  # set correct timezone
  - TZ=Europe/Berlin
  # set Sakuli test suite
  - SAKULI_TEST_SUITE=/root/my_test_suites/example_xfce
  ports:
  - 5911:5901

sakuli-example-ubuntu:
  image: consol/sakuli-ubuntu-xfce
  volumes:
  - ../example_test_suites:/root/my_test_suites
  environment:
  # set correct timezone
  - TZ=Europe/Berlin
  # set Sakuli test suite
  - SAKULI_TEST_SUITE=/root/my_test_suites/example_xfce
  ports:
  - 5912:5901