
:imagesdir: ../../../images

[[omd-preparation]]
==== OMD preparation
[#git-edit-section]
:page-path: docs/manual/integration/monitoring/omd-preparation.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

This chapter describes all necessary steps to prepare a OMD site with a *Nagios* compatible monitoring system to receive Sakuli test results with one of the forwarders <<omd-gearman,gearman>>, <<omd-sql-database,database>>, <<check_mk>> or <<icinga2-integration,icinga2-api>>. For some parts of this documentation, OMD with Thruk as web frontend will be presupposed, but any other Nagios based system will do also (the configuration steps may vary then).

[[omd-docker]]
===== OMD Docker image
NOTE: If you want to run OMD-Labs in a container then check out the https://github.com/ConSol/omd-labs-docker[OMD-Labs on Docker project].

===== Requirements

* *https://labs.consol.de/OMD/[OMD]* installed on a Linux operating system
* a running *OMD site*

===== Nagios configuration
Use the Makefile located in `$OMD_ROOT/share/sakuli/omd` to

* install predefined Nagios/Naemon service templates
* install the Sakuli logo
* enable HTML interpretation in the service output

[source]
----
OMD[demo]:~/share/sakuli/setup/omd$ make config
----

Now choose one of the <<forwarders>>.
