
:imagesdir: images

[[dev-new-release]]
=== How to create a new release
[#git-edit-section]
:page-path: docs/manual/development/how-to-release.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

* Check if all features are merged in dev
* Check if `changelog.adoc` is correct

.(Jenkins CI) Perform a new official release

. Go to http://labs-build.consol.de/job/Sakuli_perform_release/[Jenkins - Sakuli_perform_release] and execute the job and set the parameters `REL_VERSION` and `DEV_VERSION`
. Check if maven artifacts have been deployed at https://labs.consol.de/maven/repository/org/sakuli/[https://labs.consol.de/maven/repository/org/sakuli/]
. Check the new taged version on https://hub.docker.com/[DockerHub] with same `REL_VERSION` for the following images:
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=sakuli&starCount=0[DockerHub - Sakuli]
. Test the new docker images as long the https://github.com/ConSol/sakuli-examples[sakuli-examples] are not in the automated build
. Check te latest documentation is updated at http://consol.github.io/sakuli/.
. Make a new https://github.com/ConSol/sakuli/releases[GitHub Release]:
** Add `sakuli-vXXX-installer.jar` and `sakuli-vXXX.zip` from https://labs.consol.de/sakuli/install/[https://labs.consol.de/sakuli/install/] to a new release XXX
** Copy the latest changelog to the new release page
** Check and publish new release

.(local) Process a new release with maven

*1. Dry-run (if needed)*

Generate a new release over *gitflow-maven-plugin* (branch: `release/xxx`):

[source]
----
    mvn gitflow:release-start
----

Do a dry-run _without_ deploying and pushing any new files:

[source]
----
    mvn clean install -DperformRelease=true
----

Delete all local git changes and branches

*2. Release*

Generate a new release (if not done in step 1) over *gitflow-maven-plugin* (branch: `release/xxx`):

[source]
----
    mvn gitflow:release-start
----

Execute the following commands, to update the Dockerfiles to the new release version at the branch `release/xxx` .

[source]
----
    docker/update_sakuli_version.sh --new-version $REL_VERSION
    git commit -am "update Dockerfiles to REL-Version v$REL_VERS"
----

Start the release deploying and pushing any new branches and tags if needed:

[source]
----
    mvn gitflow:release-finish
----

Go to the `dev` branch and adjust the version of the Dockerfiles:

[source]
----
    docker/update_sakuli_version.sh --new-version $DEV_VERS
    git commit -am "update Dockerfiles to DEV-Version v$DEV_VERS"
----

Push your changes in `dev` branch:

[source]
----
git push --all
----

.Troubleshooting

*Re-use a tag*

To re-use an already set tag, remove it from git (local and remote):

[source]
----
# delete the tag locally:
git tag -d sakuli-X.X.X`
# push to remote:
git push --delete origin sakuli-X.X.X`
----

*General*

* Check your maven settings in `~/.m2/settings.xml`:
* Ensure that your private key has access rights for user `sakuli@labs.consol.de`
* Ensure that your private key is added to ssh-agent: `ssh-add <path-to-key>`
* Check proxy settings - the server `labs.consol.de` must be reachable
* Ensure that the ConSol-Labs server is configured correctly, see <<sql-database>>
