FROM mysql:5.5

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"

ENV REFRESHED_AT 2015-04-23
ENV MYSQL_ROOT_PASSWORD=sakuli
ENV MYSQL_DATABASE=sakuli
ENV MYSQL_USER=sakuli
ENV MYSQL_PASSWORD=sakuli

#WORKDIR /sakuli-inst
#
#ADD . /sakuli-inst

#CMD ["mysqld"]
#CMD ["/usr/local/mysql/bin/mysql -u sakuli -p sakuli sakuli <  \/sakuli-inst\/create_sakuli_database.sql"]
EXPOSE 3306
