
:imagesdir: images
[[download]]
== Download

[#git-edit-section]
:page-path: docs/download.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

.Installer
*Platform independent Java installer: https://labs.consol.de/sakuli/install/sakuli-${sakuli.version}-installer.jar[sakuli-${sakuli.version}-installer.jar^]*

.Maven Dependencies
See <<maven-execution>>.

.Docker images
See <<containerized-execution>>

.Raw ZIP
Raw Sakuli installation directory, containing Sakuli, Sahi and examples: https://labs.consol.de/sakuli/install/sakuli-${sakuli.version}.zip[sakuli-${sakuli.version}.zip^]

.PDF manual
This manual as one PDF document: link:${pdf.path}[Download PDF^]

== Branches & build status
|===
|branch |build state |docker images state

|`master`
|image:http://labs-build.consol.de/buildStatus/icon?job=Sakuli_perform_release[Build Status,link=http://labs-build.consol.de/view/Sakuli/job/Sakuli_perform_release/^]
|`consol/sakuli-ubuntu-xfce`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce.svg[dockerhub state,link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce^]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce^]

`consol/sakuli-centos-xfce`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce/^]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce^]

`consol/sakuli-ubuntu-xfce-java`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce-java.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce-java/^]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce-java.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce-java^]

`consol/sakuli-centos-xfce-java`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce-java.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce-java/^]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce-java.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce-java^]


|`dev`
|image:http://labs-build.consol.de/buildStatus/icon?job=Sakuli_CI[Build Status,link=http://labs-build.consol.de/view/Sakuli/job/Sakuli_CI/^]
|`consol/sakuli-ubuntu-xfce:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce:dev.svg[dockerhub state,link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce^]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce^]


`consol/sakuli-centos-xfce:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce:dev.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce/^]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce^]

`consol/sakuli-ubuntu-xfce-java:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce-java:dev.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce-java/^]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce-java:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce-java^]

`consol/sakuli-centos-xfce-java:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce-java:dev.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce-java/^]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce-java:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce-java^]

|===
