
:imagesdir: images
[[download]]
== Download

[#git-edit-section]
:page-path: docs/download.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

.Installer
Our Java based installer or the raw ZIP file can be downloaded form http://labs.consol.de/sakuli/install/[labs.consol.de/sakuli/install^]:

* https://labs.consol.de/sakuli/install/sakuli-${sakuli.version}-installer.jar[sakuli-${sakuli.version}-installer.jar^]
* https://labs.consol.de/sakuli/install/sakuli-${sakuli.version}.zip[sakuli-${sakuli.version}.zip^]

.Maven Dependencies
See <<_maven_execution>>.

.Docker images
See <<_containerized_execution>>


.PDF-Documentation
*link:${pdf.path}[Download PDF^]*

.branches & builds
|===
|branch |build state |docker images state

|`master`
|image:http://labs-build.consol.de/buildStatus/icon?job=Sakuli_perform_release[Build Status,link=http://labs-build.consol.de/view/Sakuli/job/Sakuli_perform_release/]
|`consol/sakuli-ubuntu-xfce`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce.svg[dockerhub state,link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce]

`consol/sakuli-centos-xfce`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce/]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce]

`consol/sakuli-ubuntu-xfce-java`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce-java.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce-java/]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce-java.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce-java]

`consol/sakuli-centos-xfce-java`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce-java.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce-java/]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce-java.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce-java]


|`dev`
|image:http://labs-build.consol.de/buildStatus/icon?job=Sakuli_CI[Build Status,link=http://labs-build.consol.de/view/Sakuli/job/Sakuli_CI/]
|`consol/sakuli-ubuntu-xfce:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce:dev.svg[dockerhub state,link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce]


`consol/sakuli-centos-xfce:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce:dev.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce/]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce]

`consol/sakuli-ubuntu-xfce-java:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-ubuntu-xfce-java:dev.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-ubuntu-xfce-java/]
image:https://images.microbadger.com/badges/image/consol/sakuli-ubuntu-xfce-java:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-ubuntu-xfce-java]

`consol/sakuli-centos-xfce-java:dev`
image:https://images.microbadger.com/badges/version/consol/sakuli-centos-xfce-java:dev.svg[dockerhub state, link=https://hub.docker.com/r/consol/sakuli-centos-xfce-java/]
image:https://images.microbadger.com/badges/image/consol/sakuli-centos-xfce-java:dev.svg[microbadger profile, link=http://microbadger.com/images/consol/sakuli-centos-xfce-java]

|===