
= Events

[#git-edit-section]
:page-path: docs/events.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

April 27, 2017: http://www.jugs.de/tt2017/abstracts.html#link07[Stuttgarter Test-Tage, Stuttgart]: Testing - Selenium? Rich-Clients? Containers? (Tobias Schneck)

January 30 - February 3, 2017: http://www.oop-konferenz.de/[OOP 2017, Munich] (Tobias Schneck)

January 19, 2017: https://www.meetup.com/de-DE/Agile-Testing-Munich/events/235148329/[Agile Testing Meetup - Testen im Zeitalter von Containern, Munich] (Tobias Schneck)

'''

November 16, 2016: http://www.containerconf.de/[ContainerConf 2016, Mannheim] (Tobias Schneck)

November 3, 2016: https://www.qs-tag.de[Software QS-Tag 2016, Nuremberg] (Tobias Schneck)

September 30, 2016: http://www.jug-saxony-day.org/[JUG Saxony Day, Dresden] (Tobias Schneck)

August 31, 2016: http://www.herbstcampus.de/programm.php[Herbstcampus 2016, Nuremberg] (Tobias Schneck)

July 25, 2016: http://www.jugm.de/[JUG M端nchen] (Tobias Schneck)

June 27, 2016 http://www.meetup.com/de-DE/Docker-Hamburg/events/229808506[Meetup during the ContainerDays, Hamburg] (Tobias Schneck)

March 8-10, 2016: http://www.javaland.eu/de/home/[JavaLand, Br端hl] (Tobias Schneck)

March 3, 2016: https://www.consol.de/von-monitoring-bis-managed-service/[Allianz Arena M端nchen] (Simon Meggle)

March 1, 2016: https://www.icinga.org/community/events/icinga-camp-berlin/[Icinga Camp, Berlin] (Simon Meggle)

January 26, 2016: https://www.xing.com/communities/groups/linux-stammtisch-muenchen-1057878[Linux-Stamtisch M端nchen] (Tobias Schneck)

'''

October 24, 2015: http://ubucon.de/2015/[Ubucon Berlin] (Simon Meggle)

October 13, 2015: https://www.consol.de/testing-integration-day-mit-redhat/[Testing &amp; Integration Day, Allianz Arena Munich] (Tobias Schneck)

June 22, 2015: http://www.meetup.com/de-DE/Agile-Testing-Munich/events/222659146/?eventId=222659146[Agile Testing Munich] (Tobias Schneck)

May 14, 2015: http://2015.opentechsummit.net/[OpenTechSummit] (Simon Meggle)

March 28, 2015: https://www.luga.de/Aktionen/LIT-2015/[LinuxTag Augsburg] (Simon Meggle)

//TODO add links to event like, (link:link[Slides])

.Slides

2017: http://www.slideshare.net/TobiasSchneck/containerized-end2end-testing-agile-testing-meetup-at-sddeutsche-zeitung-munich-19012017[Containerized End-2-End-Testing - Agile Testing Meetup Munich] (Tobias Schneck)

2016: http://www.slideshare.net/TobiasSchneck/containerized-end2end-testing-jug-saxony-day[Containerized End-2-End-Testing (German) - JUG Saxony Days Dresden] (Tobias Schneck)

2016: https://speakerdeck.com/toschneck/containerized-end-2-end-testing-containerdays-2016-in-hamburg[Containerized End-2-End-Testing - ContainerDays 2016 Hamburg] (Tobias Schneck)

2014: https://rawgit.com/toschneck/presentation/sakuli-dev-day-presentation/index.html#/[End-to-end testing
for web sites and common UIs with full Nagios integration] (Tobias Schneck)