
:imagesdir: images

[[publications]]
= Publications

[#git-edit-section]
:page-path: docs/publications.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

01/2017: https://www.consol.de/fileadmin/pdf/news/news-events/01_2017-Java_aktuell-Magazin-Christoph-Deppisch-und-Tobias-Schneck_Automatisiertes-Testen-in-Zeiten-von-Microservices.pdf[Java aktuell: Automatisiertes Testen in Zeiten von Microservices] (Christoph Deppisch / Tobias Schneck)

10/2016: https://www.informatik-aktuell.de/entwicklung/methoden/graphical-user-interface-gui-in-containern-testen.html[Informatik Aktuell: Software-Test im Container: So können Sie Graphical User Interfaces mit Docker und Sakuli testen] (Tobias Schneck)

10/2016: https://labs.consol.de/sakuli/development/2016/10/14/sakuli-java-dsl.html[ConSol Labs: Containerized UI-Tests in Java with Sakuli and Docker] (Tobias Schneck)

10/2016: https://labs.consol.de/android/monitoring/sakuli/2016/10/10/android-sakuli.html[ConSol Labs: Sakuli EndToEnd Tests mit Android] (Philip Griesbacher)

8/2016: http://www.heise.de/developer/artikel/Testautomatisierung-in-Zeiten-von-Continuous-Delivery-3300566.html[heise Developer: Testautomatisierung in Zeiten von Continuous Delivery] (Christoph Deppisch / Tobias Schneck)

8/2016: https://www.consol.de/it-services/news/details/testautomatisierung-darf-nicht-bei-unit-tests-halt-machen-1/[Pressemitteilung:
Testautomatisierung darf nicht bei Unit-Tests Halt machen ]

2/2016: https://www.consol.com/fileadmin/pdf/news/success_stories/ConSol_SuccessStory_Monitoring-Sakuli_Pfandbriefbank_eng.pdf[Success Story: pbb Deutsche Pfandbriefbank: Monitoring with Sakuli]

2/2016: http://www.it-administrator.de[IT Administrator]: http://shop.heinemann-verlag.de/it-administrator/einzelhefte/139/ausgabe-februar-2016-it-support-und-troubleshooting["Den Anwender simuliert"] (Simon Meggle)

5/2015: http://www.heise.de/developer/meldung/End-to-End-Application-Monitoring-mit-Sakuli-2729493.html[heise Developer: End-to-End Application Monitoring mit Sakuli]

2/2015: http://www.it-administrator.de[IT Administrator]: http://www.it-administrator.de/themen/netzwerkmanagement/fachartikel/179023.html[End2End-Monitoring mit dem Open Source-Tool Sakuli] (Simon Meggle)