
:imagesdir: images

[[why-sakuli]]
== Why Sakuli?

[#git-edit-section]
:page-path: docs/why-sakuli.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

There are already a variety of free end2end/automation tools on the market (Sahi, Selenium, WebInject, Sikuli, CasperJS, AutoIT , …), but each of them has at least one of the following drawbacks:

* *Too specifically*: _pure_ web testing tools can only deal with _pure_ web content. Applets, Flash, dialogues generated by OS, browser dialogues etc. are invisible and a insurmountable hurdle for such tools.
* *Too generic*: screen-based testing tools "see" everything the user sees. They are the best choice for GUI tests, but inappropriate for web tests, because each browser type has its own understanding of how to render and display a web page.
* *Far from reality*: There are tools to test web applications on protocol level - but to know whether a web application is working or not requires a test from the user's perspective.
* *Inflexible*: Hardly one of these tools brings the ability to integrate into other systems (like Nagios or Jenkins).
