---
- name: Configure core
  gather_facts: False
  hosts: all
  tasks:
    - name: pretask
      include: pretasks.yml
    - name: initialize tmp filesystem
      shell: omd start core && omd stop core
    - name: Core - eventhandler script
      copy: 
        src: ./omd/local/lib/nagios/plugins/sakuli_screenshot_eventhandler.sh
        dest: "{{ OMD_ROOT }}/local/lib/nagios/plugins/"
        mode: 0775
    - name: Core - eventhandler command
      copy: 
        src: ./omd/etc/nagios/conf.d/sakuli_screenshot_eventhandler.cfg
        dest: "{{ OMD_ROOT }}/etc/core/conf.d/"
      notify: 
        - omd_reload_core
    - name: Core - logo directory
      file: 
        path: "{{ OMD_ROOT }}/local/share/nagios/htdocs/images/logos/"
        state: directory
        recurse: yes
    - name: Core - Sakuli logo
      copy: 
        src: ./omd/local/share/nagios/htdocs/images/logos/sakuli.png
        dest: "{{ OMD_ROOT }}/local/share/nagios/htdocs/images/logos/"
    - name: Core - Sakuli templates
      copy: 
        src: ./omd/etc/nagios/conf.d/sakuli_nagios_templates.cfg
        dest: "{{ OMD_ROOT }}/etc/core/conf.d/"
      notify: 
        - omd_reload_core
    - name: Escape HTML tags
      lineinfile: 
        path: "{{ item }}"
        regexp: '^escape_html_tags=\d$'
        line: 'escape_html_tags=0'
      ignore_errors: yes
      with_items: 
        - "{{ OMD_ROOT }}/etc/core/cgi.cfg"
        - "{{ OMD_ROOT }}/etc/thruk/cgi.cfg"
      notify: 
        - omd_reload_apache
        - omd_reload_core
  handlers: 
    - include: handlers.yml
