
:imagesdir: ../../../../images

[[omd-integration-native]]
===== Native OMD Integration
[#git-edit-section]
:page-path: docs/manual/integration/monitoring/advanced-topics/omd-native.adoc
git-link:{page-path}{git-view} | git-link:{page-path}{git-edit}

This chapter describes all necessary steps to configure a *Nagios* compatible monitoring system to receive Sakuli test results. OMD with Thruk as web frontend is highly recommended, but any other Nagios based system will do also.

====== Requirements

* *http://www.omdistro.org[OMD] 1.x* installed on a Linux operating system
* a running *OMD site* (here: *sakuli*)

====== Download

General note: you should download the *same package version of Sakuli* as you did on the clients. *Do not mix versions*. 

Download *Sakuli* from http://labs.consol.de/sakuli/install[http://labs.consol.de/sakuli/install] into a temporary folder `__TEMP__`.
[source]
----
cd __TEMP__
wget http://labs.consol.de/sakuli/install/sakuli-vx.x.x-SNAPSHOT.zip
----

Decompress it:
[source]
----
unzip sakuli-vx.x.x-SNAPSHOT.zip
----

====== General preparations

All following steps should be done as the *OMD site user* (here: "sakuli"):

[source]
----
su - sakuli
----

*Nagios*

Sakuli will produce HTML formatted output. *HTML escaping* in Nagios must be turned off: 

[source]
----
OMD[sakuli]:~$ vim etc/nagios/cgi.cfg
    escape_html_tags=0
----

====== Choose a forwarder

Depending on your environment, you can set up on of these two possible forwarder types. Each of them is documented on a single page.

* link:#omd-gearman[Setting up Nagios to *receive Gearman results* from Sakuli clients] (**recommended**)
** passive check (via Gearmand result queue)
** + get results immediately
** + PNP graphs
** - no performance value history to do further reporting (despite reading the RRDs again; not recommended)
* link:#omd-sql-database[Setting up the Sakuli *result database* in OMD] and let Nagios check the database
** active check (against MySQL result database)
** - results in Nagios always lag behind
** + PNP graphs
** + all suite/case/step performance values are stored in database and can be used for further reporting

//TODO mention PNP + delivered default templates
